# Generated by Django 3.2.6 on 2021-08-30 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.IntegerField(null=True, verbose_name='شماره دانشجویی')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='عنوان پیام')),
                ('upload', models.FileField(blank=True, upload_to='media', verbose_name='ارسال فایل')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس پیام')),
                ('contentmsg', models.TextField(verbose_name='متن پیام')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.IntegerField(null=True, verbose_name='شماره دانشجویی')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='عنوان فایل')),
                ('upload', models.FileField(blank=True, upload_to='media', verbose_name='ارسال فایل')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='آدرس فایل')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کدکاربری')),
                ('password', models.CharField(max_length=100, verbose_name='رمز ورود')),
                ('firstname', models.CharField(max_length=70, null=True, verbose_name='نام')),
                ('lastname', models.CharField(max_length=70, null=True, verbose_name='نام خانوادگی')),
                ('mobil', models.CharField(max_length=50, null=True, verbose_name='شماره تلفن همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
